module.exports = {
  DEFAULT_PORT: 4444,
  COIN_MARKET_CAP_API_ENDPOINT:
    "https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest",
  COIN_MARKET_CAP_API_KEY: "06996bb9-2f6f-4c2c-91ce-4fba792989f6",
  COIN_MARKET_CAP_API_KEY_HEADER: "X-CMC_PRO_API_KEY",
  EXCHANGE_RATES_API_ENDPOINT: "https://api.exchangeratesapi.io/latest",
  EXCHANGE_RATES_API_BASE_CURRENCY_QUERY_NAME: "base",
  EXCHANGE_RATES_API_BASE_CURRENCY_QUERY_VALUE: "USD",
  EXCHANGE_RATES_API_SYMBOL_CURRENCY_QUERY_NAME: "symbols",
  EXCHANGE_RATES_API_SYMBOL_CURRENCY_QUERY_VALUE: "GBP,BRL,EUR,AUD"
};
